### ISSUE TITLE
Custom Iosevka Font

### ISSUE THREAD

**Issue by tanmayr2** [alfunx/.dotfiles#3]
Hey, can't figure out the Iosevka font you used in the screenshot in your README. Searching dotfiles, it appears to to Iosevka Custom.
There was a ttf-iosevka-custom-git AUR package, I figured it was that, but apparently not. The spacing b/w your characters seems to be wider. 
Could you share your custom font or give any pointers?
Here is my screenshot:
![Vim Screenshot](https://user-images.githubusercontent.com/33316803/47961586-ef724f00-e033-11e8-99fd-9e89b784c905.png)

**Comment by alfunx** [comment]
I use a customized version of the Iosevka font. You can find the configuration file, as well as the PKGBUILD in the `packages` directory, here: https://github.com/alfunx/.dotfiles/tree/master/packages/iosevka

> The spacing b/w your characters seems to be wider.

I'm using the `expanded` setting, which makes the characters wider.
