### ISSUE TITLE
Awesome theme not loaded

### ISSUE THREAD

**Issue by rockyhotas** [alfunx/.dotfiles#4]
Presenting [this theme](https://github.com/awesomeWM/awesome/issues/1395#issuecomment-396733091), you mentioned this dotfiles repository. I cloned it to apply the theme, using AwesomeWM 4.2 on NetBSD 8.0. However, it doesn't work, showing two error messages:

```
Oops, an error happened!
invalid key to 'next'
```

```
Oops, there were errors during startup!
error while running function!
stack traceback:
[C]: in function 'key'
/usr/pkg/share/awesome/lib/awful/key.lua:88: in function </usr/pkg/share/awesome/lib/awful/key.lua:80>
(...tail calls...)
/home/userdir/.config/awesome/config/keys.lua:421:in function 'init'
/home/userdir/.config/awesome/rc.lua:103: in main chunk
```

I do not know the `lua` language. Is there anything I can do?

**Comment by alfunx** [comment]
Can you try to comment (or delete) the marked lines: https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/config/keys.lua#L416-L439

Thanks for reporting, this doesn't happen with the current Git version of AwesomeWM though.

**Comment by rockyhotas** [comment]
> Can you try to comment (or delete) the marked lines: [.config/awesome/config/keys.lua:416-439](https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/config/keys.lua#L416-L439)

Ok! Unfortunately, the result is another error:

```
Oops, an error happened!
/home/userdir/.config/awesome/config/screen.lua:51: attempt to call field 'at_screen_connect' (a nil valu...
```

```
Oops, there were errors during startup!
error while running function!
stack traceback:
	/home/userdir/.config/awesome/config/screen.lua:51: in function 'func'
	/usr/pkg/share/awesome/lib/awful/screen.lua:438: in function 'connect_for_each_screen'
	/home/userdir/.config/awesome/config/screen.lua:49: in function 'init'
	/home/userdir/.config/awesome/rc.lua:108: in main chunk
error: /home/userdir/.config/awesome/config/screen.lua:51: attempt to call field 'at_screen_connect' (a n...
```

> Thanks for reporting, this doesn't happen with the current Git version of AwesomeWM though.

You're welcome. Surely, the version of AwesomeWM in pkgsrc (4.2nb3, the one I'm using) is older.

**Comment by alfunx** [comment]
> Surely, the version of AwesomeWM in pkgsrc (4.2nb3, the one I'm using) is older.

It is very recent; what I meant to state is that it's something that has been fixed.

This second error is unrelated to the first one. Your second logs provides some useful information:

```
stack traceback:
	/home/userdir/.config/awesome/lain/widget/mem.lua:37: in function 'func'
	/usr/pkg/share/awesome/lib/gears/object.lua:118: in function 'emit_signal'
	/home/userdir/.config/awesome/lain/helpers.lua:96: in function 'newtimer'
	/home/userdir/.config/awesome/lain/widget/mem.lua:45: in function 'mem'
	/home/userdir/.config/awesome/themes/blackout/theme.lua:391: in main chunk
```

In this case `mem` (the memory widget) is causing the error. Can you try to comment out [.config/awesome/themes/blackout/theme.lua:1145](https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/themes/blackout/theme.lua#L1145) (`mem_widget` is a wrapper widget around `mem`)? And also try to comment out subsequent widgets, if there are more errors. As far as I can tell so far, the origin seems to be Lain, though I'm not sure. For the other widgets, also make sure to setup the variables according to your machine: [.config/awesome/rc.lua:51-64](https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/rc.lua#L51-L64).

**Comment by voidpin** [comment]
Sorry if I'm hijacking you guys, but...
...things like lain or vicious won't work OOTB in NetBSD, they are built for Linux.
There was a port of vicious to FreeBSD, but I don't know if it's still alive. In any case, it also would need to be modified.
What I can tell is that the widgets built natively into awesome work, I use awesome on both Void and NetBSD. On Void I use vicious, on NetBSD I use only the native support.
Example - battery widget, there is no /sys/class/power_supply on NetBSD so, for example this, https://github.com/deficient/battery-widget/blob/master/README.md won't work.
Regards

**Comment by rockyhotas** [comment]
> Can you try to comment out [.config/awesome/themes/blackout/theme.lua:1145](https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/themes/blackout/theme.lua#L1145) (`mem_widget` is a wrapper widget around `mem`)? And also try to comment out subsequent widgets, if there are more errors.

I commented as suggested, but the error keeps being the same.

> As far as I can tell so far, the origin seems to be Lain, though I'm not sure. For the other widgets, also make sure to setup the variables according to your machine: [.config/awesome/rc.lua:51-64](https://github.com/alfunx/.dotfiles/blob/master/.config/awesome/rc.lua#L51-L64).

Ok, I've modified the variables, but no changes in the above error. Maybe the problem is just the one signaled by @voidpin .

**Comment by rockyhotas** [comment]
> Sorry if I'm hijacking you guys, but...

No problem, thank you instead.

> ...things like lain or vicious won't work OOTB in NetBSD, they are built for Linux.

Now I can't try with a Linux machine, but this is important to know. Thanks.

> What I can tell is that the widgets built natively into awesome work, I use awesome on both Void and NetBSD. On Void I use vicious, on NetBSD I use only the native support.

Ok! If you know any theme using only native support, and if they are not OT here, please let me know.

> Example - battery widget, there is no /sys/class/power_supply on NetBSD so, for example this, https://github.com/deficient/battery-widget/blob/master/README.md won't work.

Yes, of course: that path doesn't exist in NetBSD.

**Comment by voidpin** [comment]
@rockyhotas 
We could either continue the discussion here or move over to https://unitedbsd.com
Does this look good enough for you, https://unitedbsd.com/t/what-does-your-bsd-look-like-screen-shots/109/21?u=pin ?

**Comment by rockyhotas** [comment]
Discussion moved to [https://unitedbsd.com/t/what-does-your-bsd-look-like-screen-shots/109/24?u=rockyhotas](https://unitedbsd.com/t/what-does-your-bsd-look-like-screen-shots/109/24). It should be quite OT here, given that maybe the reason why it does not work is due to `lain` and `freedesktop`, that are not compatible with NetBSD.
Thank you :)

Note for @alfunx : there has been an upgrade available in NetBSD involving the packages

`gobject-introspection-1.56.1 lua52-gi-0.9.1 libxkbcommon-0.8.2 awesome-4.2nb3`

After applying it, however, the same error keeps appearing. Thank you so much anyway!
