### ISSUE TITLE
paclist aur and manual packages

### ISSUE THREAD

**Issue by jakobkukla** [alfunx/.dotfiles#5]
Hi

How do you paclist packages from aur? If I run paclist aur it says it could'nt find that repository. Same is true for manual.

Thanks!

**Comment by alfunx** [comment]
I have two custom repositories called `aur` and `manual`, where I put packages from the AUR and my own manually built packages. Which means, it won't work for you unless you set up those repositories as well. In my case, `aurutils` handles the building/packaging and puts the packages in the repo afterwards.

**Comment by jakobkukla** [comment]
Thanks, I notized that it doesn't work that's why I asked. :)

Thanks!
